### ISSUE TITLE
Adding wireframes

### ISSUE THREAD

**Issue by DHBW-Malte** [DHBW-Malte/RedditSentimentAnalyzer#10]
- [x] Create some wireframes
- [x] add them to the DD

**Comment by DHBW-Malte** [comment]
link to the wireframes: https://whimsical.com/web-application-wireframe-GNYbyhod38ArxB1rHQMMy8

**Comment by GT-XVII** [comment]
pls give acces @DHBW-Malte 
liamthomson118@gmail.com

**Comment by DHBW-Malte** [comment]
Done @GT-XVII

**Comment by GT-XVII** [comment]
@DHBW-Malte Looks really good! Unless you have any more ideas, I think it's ready to be added to the DD.

**Comment by DHBW-Malte** [comment]
@GT-XVII perfect! Could you export and put them into the DD? Then we could ask Elias for Feedback👍🏼
